### ISSUE TITLE
Library: RGBMood

### ISSUE THREAD

**Issue by nchpmn** [nchpmn/Project-Aurora#13]
Investigate a prebuilt library for controlling RGB - cycles, fades, etc.

https://forum.arduino.cc/index.php?topic=90160.0
https://github.com/Tibus/Arduino-RGB-Mood

Example:
```
 m.setMode(RGBMood::RANDOM_HUE_MODE);  // Automatic random fade.
 m.setHoldingTime(4000);  // Keep the same color for 4 seconds before fading again.
 m.setFadingSteps(150);   // Fade with 150 steps.
 m.setFadingSpeed(50);    // Each step last 50ms. A complete fade takes 50*150 = 7.5 seconds
 m.setHSB(random(359), 255, 255) // Random hue mode only change the hue so we first set the saturation and brightness to what we want.
```

**Comment by nchpmn** [comment]
Implementing this could require a complete rewrite of controller code.

**Comment by Doge0098** [comment]
I cant download because the Dropbox link is missing

**Comment by nchpmn** [comment]
> I cant download because the Dropbox link is missing

Hey Doge0098, this project is abandoned. Existing code can be downloaded by forking the project.
